name: Build AI VietMap Camera HUD APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Build APK
      run: |
        cd Android_Project
        gradle assembleDebug

    - name: Upload AI VietMap Camera HUD APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tool_AndroidBox_AI_VietMap_RedLight_Camera
        path: Android_Project/app/build/outputs/apk/debug/Tool_AndroidBox_AI_VietMap_Camera_HUD.apk
